import argparse
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim

from src.config import (
    ANOMALY_REPORT_PATH,
    BATCH_SIZE,
    DOMAINS,
    EARLY_STOP_PATIENCE,
    EPOCHS,
    FC_DROPOUT,
    GCN_DROPOUT,
    GCN_HIDDEN,
    GRAD_CLIP_NORM,
    GRU_HIDDEN,
    GRU_LAYERS,
    LEARNING_RATE,
    MODEL_PATH,
    NUM_NODES,
    PREDICTIONS_PATH,
    SCHEDULER_FACTOR,
    SCHEDULER_PATIENCE,
    SEQ_LEN,
    TRAIN_HISTORY_PATH,
    WEIGHT_DECAY,
)
from src.dataset import prepare_data
from src.model import GCN_GRU


DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def rmse_original_scale(preds_norm, targets_norm, target_scaler):
    preds = target_scaler.inverse_transform(preds_norm.cpu().numpy().reshape(-1, 1)).flatten()
    targets = target_scaler.inverse_transform(targets_norm.cpu().numpy().reshape(-1, 1)).flatten()
    return float(np.sqrt(np.mean((preds - targets) ** 2)))


def run_epoch(model, loader, optimizer, criterion, amp_scaler, target_scaler, train=True):
    model.train() if train else model.eval()
    total_loss = 0.0
    all_preds = []
    all_targets = []

    context = torch.enable_grad() if train else torch.no_grad()
    with context:
        for x_batch, y_batch in loader:
            x_batch = x_batch.to(DEVICE, non_blocking=True)
            y_batch = y_batch.to(DEVICE, non_blocking=True)

            if train:
                optimizer.zero_grad()

            with torch.autocast(device_type=DEVICE.type, enabled=DEVICE.type == "cuda"):
                preds = model(x_batch)
                loss = criterion(preds, y_batch)

            if train:
                amp_scaler.scale(loss).backward()
                amp_scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)
                amp_scaler.step(optimizer)
                amp_scaler.update()

            total_loss += loss.item()
            all_preds.append(preds.detach())
            all_targets.append(y_batch.detach())

    all_preds = torch.cat(all_preds)
    all_targets = torch.cat(all_targets)
    avg_loss = total_loss / len(loader)
    rmse_ms = rmse_original_scale(all_preds, all_targets, target_scaler)
    return avg_loss, rmse_ms


def collect_predictions(model, loader, target_scaler):
    model.eval()
    preds_norm = []
    targets_norm = []
    with torch.no_grad():
        for x_batch, y_batch in loader:
            preds = model(x_batch.to(DEVICE)).cpu()
            preds_norm.append(preds)
            targets_norm.append(y_batch)

    preds_norm = torch.cat(preds_norm).numpy()
    targets_norm = torch.cat(targets_norm).numpy()
    preds_ms = target_scaler.inverse_transform(preds_norm.reshape(-1, 1)).flatten()
    targets_ms = target_scaler.inverse_transform(targets_norm.reshape(-1, 1)).flatten()
    return preds_norm, targets_norm, preds_ms, targets_ms


def save_predictions(arrays, preds_norm, targets_norm, preds_ms, targets_ms):
    df_test = arrays["df_test"]
    source_index = arrays["test_source_index"]
    report = df_test.iloc[source_index].copy().reset_index(drop=True)
    report["predicted_latency_ms"] = preds_ms
    report["actual_latency_ms"] = targets_ms
    report["squared_error_norm"] = (preds_norm - targets_norm) ** 2
    PREDICTIONS_PATH.parent.mkdir(parents=True, exist_ok=True)
    report.to_csv(PREDICTIONS_PATH, index=False)
    print(f"Saved predictions: {PREDICTIONS_PATH}")


def main():
    parser = argparse.ArgumentParser(description="Train GCN-GRU for 5G slice latency prediction.")
    parser.add_argument("--data", type=Path, required=True, help="CSV path generated by src.data_generation.")
    parser.add_argument("--epochs", type=int, default=EPOCHS)
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE)
    parser.add_argument("--learning-rate", type=float, default=LEARNING_RATE)
    args = parser.parse_args()

    loaders, arrays, scalers = prepare_data(args.data, DOMAINS, SEQ_LEN, args.batch_size)
    target_scaler = scalers["target"]

    print(f"Device: {DEVICE}")
    print(
        f"Train batches: {len(loaders['train'])} | "
        f"Val batches: {len(loaders['val'])} | Test batches: {len(loaders['test'])}"
    )

    model = GCN_GRU(
        num_nodes=NUM_NODES,
        gcn_hidden=GCN_HIDDEN,
        gru_hidden=GRU_HIDDEN,
        gru_layers=GRU_LAYERS,
        gcn_dropout=GCN_DROPOUT,
        fc_dropout=FC_DROPOUT,
    ).to(DEVICE)
    optimizer = optim.Adam(model.parameters(), lr=args.learning_rate, weight_decay=WEIGHT_DECAY)
    criterion = nn.MSELoss()
    amp_scaler = torch.cuda.amp.GradScaler(enabled=DEVICE.type == "cuda")
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        patience=SCHEDULER_PATIENCE,
        factor=SCHEDULER_FACTOR,
    )

    best_val_rmse = float("inf")
    patience_counter = 0
    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    history = []

    print(f"\n{'Epoch':>5} {'Train Loss':>12} {'Train RMSE':>12} {'Val Loss':>10} {'Val RMSE':>10} {'LR':>10}")
    print("-" * 70)

    for epoch in range(1, args.epochs + 1):
        train_loss, train_rmse = run_epoch(
            model, loaders["train"], optimizer, criterion, amp_scaler, target_scaler, train=True
        )
        val_loss, val_rmse = run_epoch(
            model, loaders["val"], optimizer, criterion, amp_scaler, target_scaler, train=False
        )
        scheduler.step(val_rmse)
        current_lr = optimizer.param_groups[0]["lr"]
        history.append(
            {
                "epoch": epoch,
                "train_loss": train_loss,
                "train_rmse_ms": train_rmse,
                "val_loss": val_loss,
                "val_rmse_ms": val_rmse,
                "learning_rate": current_lr,
            }
        )

        print(
            f"{epoch:>5} {train_loss:>12.4f} {train_rmse:>11.3f}ms "
            f"{val_loss:>10.4f} {val_rmse:>9.3f}ms {current_lr:>10.2e}"
        )

        if val_rmse < best_val_rmse:
            best_val_rmse = val_rmse
            patience_counter = 0
            torch.save(model.state_dict(), MODEL_PATH)
        else:
            patience_counter += 1
            if patience_counter >= EARLY_STOP_PATIENCE:
                print(f"\nEarly stopping at epoch {epoch}")
                break

    print("\nLoading best checkpoint for test evaluation...")
    model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
    test_loss, test_rmse = run_epoch(
        model, loaders["test"], optimizer, criterion, amp_scaler, target_scaler, train=False
    )
    print(f"\nTest Loss (normalized MSE): {test_loss:.4f}")
    print(f"Test RMSE (original scale): {test_rmse:.3f} ms")

    preds_norm, targets_norm, preds_ms, targets_ms = collect_predictions(model, loaders["test"], target_scaler)
    save_predictions(arrays, preds_norm, targets_norm, preds_ms, targets_ms)
    TRAIN_HISTORY_PATH.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(history).to_csv(TRAIN_HISTORY_PATH, index=False)
    print(f"Saved training history: {TRAIN_HISTORY_PATH}")
    print(f"Run SHAP next with: python -m src.explain_shap --data {args.data}")


if __name__ == "__main__":
    main()
